language: haskell

ghc:
  # GHC 7.4.* is not supported by tagged-exception-core Cabal package.
  - 7.8
  - 7.6

script:
  # Option -fpedantic turns on additional wornings in addition to -Wall.
  - cabal configure -fpedantic && cabal build

  # Following line tests if sdist package is created correctly.
  - cabal sdist && cabal install dist/lock-file-*.tar.gz
